server:
  port: 18200
spring:
  application:
    name: springCloudClient
eureka:
  instance:
    hostname: ${spring.application.name}
    preferIpAddress: true
#    instance-id: ${spring.application.name}:8761
  client:
    serviceUrl:
#      defaultZone:
      defaultZone: http://localhost:8761/eureka