server:
  port: 18100
spring:
  application:
    name: springCloudServer
eureka:
  instance:
    hostname: ${spring.application.name}
    preferIpAddress: true
#    instance-id: ${spring.application.name}:8761
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka