server:
  port: 18100
spring:
  application:
    name: springCloudServer
eureka:
  instance:
    hostname: ${spring.application.name}
    preferIpAddress: true
    instance-id: ${spring.application.name}:${random.value}
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka